### PR TITLE
Dfr 909 disallow trial bundle

### PR DESCRIPTION
**Pull request by gmikerlemos**
https://tools.hmcts.net/jira/browse/DFR-909

### CODE REVIEW

**Review by EllisD-B — APPROVED** [review]
Since the refactor here isn't a natural consequence of the functional change for the ticket, it's probably better practice to do both of these on separate branches in future

**Comment by rishikrsharma** [comment]
Too big PR - mostly refector code - Might be good idea create separate ticket then do refector:
scope of this ticket is not refector

**Comment by gmikerlemos** [comment]
> Too big PR - mostly refactor code - Might be good idea create separate ticket then do refector:
> scope of this ticket is not refector

It is not big, mostly tiny refactors to several files, and should be straightforward to review if looked into it. I disagree that a pr should be created to refactor what was refactored here.

**Comment by rishikrsharma** [comment]
> > Since the refactor here isn't a natural consequence of the functional change for the ticket, it's probably better practice to do both of these on separate branches in future
> 
> You should always refactor code that you bump into if it doesn't become a major change, I disagree when you say the refactor here is not a consequence of the feature, it is related to UploadCaseFile event-related classes and if you think like this most refactors wouldn't be done. The best practices say you should continuously refactor your codebase, preferably in small chunks like here. I would agree if we were refactoring all service classes to become handlers, that would be a big change, and guess what, I created a tech debt ticket for that, but if we all start refactoring the services little by little that tech debt ticket will become easier when it's picked up. This is my view, but I will accept a different approach if it is a team-wide decision. Your views @ruban72 ?

Let @ruban72 to decide. Still for me - This PR should only be ticket related change, rest of the change should be separate.

**Pull request merged**
